### ISSUE TITLE
FormatException

### ISSUE THREAD

**Issue by addreeh** [rinukkusu/spotify-dart#188]
Hi guys, any idea about this issue:

FormatException: Unexpected character (at character 1)
Too many requests

I dont know if is an API timeout, if it is which will be the better solution?

**Comment by rinukkusu** [comment]
Seems like you hit a quota and got rate limited. But maybe we need to think about some library level handling of such a situation.

What it means for you right now is, that you need to wait until you can make a request again. In the [Developer Dashboard](https://developer.spotify.com/dashboard) you should be able to see your current volume.

**Comment by hayribakici** [comment]
@addreeh You could show the user a message, that the app is currently not usable and that he/she should try it again later. I suggest to check the code for unnecessary requests (sometimes they are done in some `for`-loops) and look for alternatives (e.g. instead of requesting all albums for each artist, you could collect each `albumId` for each artist and do a `getSeveralAlbums` request). That way you would reduce requests.

**Comment by hayribakici** [comment]
```dart
while (true) {
      try {
        var tracks = await spotifyApi.playlists
            .getTracksByPlaylistId(playlistObject.id)
            .getPage(limit, offset);
...
}
```

1. So one thing, that looks suspicious is that you fetch **all** playlist items. If - let's say - a playlist has 300 tracks, but only - let's say - 15 are displayed, then it is indeed a waste of requests. As far as I understand your code, you want to display tracks from a playlist in a list (?). You could reduce requests by only `GET`ting one `Page` at a time. This could be done with `ListView`s that allow to fetch more data once the end of the list is reached. Unfortunately I forgot the proper name of those lists, but with a quich search you would be able to find it.

------

```dart
_getFullArtist() async {
    List<spotify.Artist> artists = [];
    for (var artist in playlistArtists) {
      try {
        var newArtist = await spotifyApi.artists.get(artist.id);
        artists.add(newArtist);
      } catch (e) { ... }
    return artists;
  }
```

2. You could use `spotify.artists.list()` here instead of requesting each artist individually. So in your case it would look like this:

```dart
_getFullArtist() async {
    // converting list of artists into list of artist id's
    var artistIds = playlistArtists.map((artist) => artist.id);
    // bulk retrieve artist information saving you the for-loop
    return await spotifyApi.artists.list(artistIds);
  }
```

Hope it helps :)

**Comment by hayribakici** [comment]
> Seems like you hit a quota and got rate limited. But maybe we need to think about some library level handling of such a situation.

Maybe tracking the number of requests?

**Comment by hayribakici** [comment]
@addreeh You can check out the [wiki-page](https://github.com/rinukkusu/spotify-dart/wiki/Implemented-endpoints), where all implemented endpoints are listed.

**Comment by hayribakici** [comment]
I tried your app out, and retrieving each track and having a statistic like that, is also the only way I would come up with. But I think, you could optimize some of your `for` loops, for example

```dart
int offset = 0;
    int limit = 100;

    while (true) {
      try {
        var tracks = await spotifyApi.playlists
            .getTracksByPlaylistId(playlistObject?.id ?? '')
            .getPage(limit, offset);
        if (tracks.items != null && tracks.items!.isNotEmpty) {
          try {
            songs.addAll(tracks!.items); //<-- just use addAll instead of another for loop.
            offset += limit;
          } catch (e) {
            offset = songs.length;
          }
```

And you also could play around with the [dart collection](https://dart.dev/language/collections) api. It has some methods that could make you remove some of your `for` loops.

**Comment by hayribakici** [comment]
@addreeh can this issue be closed?
