### ISSUE TITLE
Log In Account

### ISSUE THREAD

**Issue by addreeh** [rinukkusu/spotify-dart#190]
Is there any way to log in with an spotify account easily? I mean for example clicking a button and redirecting the user to the spotify log in or something like that?
![image](https://github.com/rinukkusu/spotify-dart/assets/74270582/9c7c0e69-ecc2-416e-a0d7-c4e36295308f)

**Comment by hayribakici** [comment]
I will take a look at this this week.

for future issues, if you have to paste long code, I suggest using the `<details></details>` toggle:

<details>
<summary>Expand</summary>

* Bullet
* Points
* and stuff

</details>

```markdown

<details>
<summary>Expand</summary>

* Bullet
* Points
* and stuff

</details>
```

moreover, you could also just reference the file (or mention the file name), if it is in this library. No need to paste the whole file.

And finally, you can use code highlighting with 
````
```dart
<your code here>
```
````

**Comment by hayribakici** [comment]
I am not sure, how `localhost` is available on mobile devices. I think you have to give spotify a real `responseUrl` (e.g. your github profile page).
(I am not 100% sure of this, though. Maybe @rinukkusu knows more about this)

**Comment by ahmedo100** [comment]
Just to have more inputs about this, does that mean you guys are thinking of adding support to other login flows available in the spotify sdk?

**Comment by hayribakici** [comment]
@ahmedo100 since spotify is not supporting any other login flows other than the one mentioned in their documentation, I would say, no.

**Comment by hayribakici** [comment]
This maybe a hack but what you could do is to include the spotify android and ios sdk into your flutter app and call the android login activity (for android) from your flutter app. Since you are then getting some sort of client secret from spotify, you could bind it in your flutter app. 
I haven't tried this and I don't know if that is even possible, that is the first thing that came into my mind when I lookend into the android sdk documentation. If anyone knows more, that would be great.

**Comment by hayribakici** [comment]
Since we cannot help any further, I would like to close this issue @addreeh .
