### ISSUE TITLE
Search returns Album, but json only contains SimplifiedAlbum

### ISSUE THREAD

**Issue by fdietze** [rinukkusu/spotify-dart#39]
First, thanks for the great library! It already made my life easier. :)

I got bitten by this bug using the search API and searching for albums. I was accessing the `popularity` field and got a null pointer exception.

The Spotify API Reference, states, that simplified album objects are returned from search:
https://developer.spotify.com/documentation/web-api/reference-beta/#category-search

So I think that trying to detect Simplified or Full Album types automatically using this heuristic is problematic. We should stick to types stated in reference documentation here.

https://github.com/rinukkusu/spotify-dart/blob/a4c59e347a45734161332483605e6bd5cec50ceb/lib/src/models/album.dart#L51

**Comment by rinukkusu** [comment]
In a past issue (https://github.com/rinukkusu/spotify-dart/issues/15) the problem was stated that the search api sometimes seems to return simplified album objects and sometimes not. I'm not sure if this has changed now or what's the current state.

You're right, though - I'm not the biggest fan of that heuristic either!

Will think about what to do :)

**Comment by rinukkusu** [comment]
Done 🙂
