### ISSUE TITLE
Spotify podcast API

### ISSUE THREAD

**Issue by maku** [rinukkusu/spotify-dart#40]
It would be cool when spotify-dart also support the Podcast API -> https://developer.spotify.com/community/news/2020/03/20/introducing-podcasts-api/

**Comment by rinukkusu** [comment]
Hi @maku, sounds like a great idea! Do you want to try and add the endpoints with a PR? We can assist you, should you need help along the way!

At the moment I sadly don't really have the time to add such big new things myself..

**Comment by deandreamatias** [comment]
I can do this. I need for personal project
This week maybe

**Comment by deandreamatias** [comment]
@rinukkusu 
I try use [this endpoint](https://developer.spotify.com/console/get-show-episodes/?offset=1&limit=2&id=38bS44xjbVVZ3No3ByF1dJ) and API return 404.

But in [this similar endpoint](https://developer.spotify.com/console/get-several-shows/) works fine.
Is because 
Show episode endpoint, need a scope and get several shows no. Maybe this is the problem? I need the complex authentication?
![image](https://user-images.githubusercontent.com/21011641/97036251-d8ea9880-1567-11eb-9345-52ef8fdc2481.png)

**Comment by hayribakici** [comment]
@deandreamatias can this issue be closed?

**Comment by deandreamatias** [comment]
> @deandreamatias can this issue be closed?

@hayribakici No, because podcast API has more endpoint to include in this package

**Comment by hayribakici** [comment]
@deandreamatias I would create separate issues for the missing endpoints and close this one, since the according branch has already been merged.

**Comment by rinukkusu** [comment]
@maku more endpoints coming later :)

see #78
