### ISSUE TITLE
Playlist support

### ISSUE THREAD

**Issue by RaulOlmedoCheca** [rinukkusu/spotify-dart#5]
Hi! I found your library while playing with the Spotify API, I just wanted to make sure that I'm not missing something and playlists just aren't supported at the moment (maybe I don't know how to use them, really).
Great work!

**Comment by rinukkusu** [comment]
We currently have not everything implemented but you should be able to access some features:

```dart
var featuredPlaylists = spotify.playlists.featured.items;
var myPlaylists = spotify.playlists.me.items;
```

If you need something specific, maybe try and implement it and send us a pull request.
Otherwise we can look into it and add it when we find the time. 

https://github.com/rinukkusu/spotify-dart/blob/master/lib/src/endpoints/playlists.dart

**Comment by RaulOlmedoCheca** [comment]
I'll try to implement it by myself to learn.
Could you please provide me with an example usage of pagination? I'm having a hard time trying to figure how to use them to obtain more items than the default ones.

**Comment by RaulOlmedoCheca** [comment]
I'll try to implement it to learn. I came up with a problem, do you handle the scopes of the authorization with Spotify or not?
Thanks again and sorry to bother

**Comment by RaulOlmedoCheca** [comment]
Whenever you are ready to help others contribute to this library reopen this issue at your will.
Regards

**Comment by rinukkusu** [comment]
Thanks for trying!
