### ISSUE TITLE
Currently Playing stream?

### ISSUE THREAD

**Issue by shinyford** [rinukkusu/spotify-dart#71]
Apologies in advance for my ignorance...

Is it possible to receive a Currently Playing stream that is updated only when there's a change? For example, when a track finishes and a new one begins; or when a track is paused or restarted? (I guess I'm asking if there's a pubsub client for the spotify api, or something like that.)

At the moment I'm polling `spotifyApi.me.currentlyPlaying()` every three seconds, which is not ideal.

Many thanks

Nic

**Comment by roisnir** [comment]
Hi Nic!
This package warps Spotify's web api, which is based on http requests. You get data as a response to your request rather than listening to events.
However spotify web/android/ios sdk's implements what you are looking for.
Take a look on [this flutter plugin](https://pub.dev/packages/spotify_sdk), I haven't used it but according to the documentation `subscribeToPlayerState` is implemented.

**Comment by shinyford** [comment]
Thanks for the reply - I'll take a look. Cheers!

**Comment by roisnir** [comment]
Happy to help. I'm closing the issue for now, If you have further questions reopen it.
