### ISSUE TITLE
Update library description

### ISSUE THREAD

**Issue by deandreamatias** [rinukkusu/spotify-dart#76]
In [this line](https://github.com/rinukkusu/spotify-dart/blob/3dcbc3c102b6938bcfc0bc3ea8aa189bfa0f7a4c/pubspec.yaml#L2) say 'An incomplete library'
Maybe can update this to: 

> A dart library for interfacing with the Spotify API.

If this library is under construction, maybe indicate in README

**Comment by hayribakici** [comment]
Maybe we should create another issue for that?

**Comment by rinukkusu** [comment]
I'm not entirley sure what the problem seems to be. The discrepancy between the description in the `pubspec.yaml` and the README? 

To be factually correct: the library is incomplete and back then I wanted to let people know. Right now we probably already cover most of the common use cases, but still are far from complete. Maybe we can add a section in the README or Wiki with all the endpoints that are currently implemented.

**Comment by hayribakici** [comment]
Oops it seems like I posted into the wrong issue. I meant to create another issue regarding #75. Sorry.

**Comment by deandreamatias** [comment]
If library is incomplete yet, then this isn't a issue
